### ISSUE TITLE
Learn.md

### ISSUE THREAD

**Issue by Princegupta101** [usha-madithati/esmart.github.io#10]
Learn repos should have a LEARN.md file to teach student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn.

Reference: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/Learn.md

**Comment by Gokilp** [comment]
please assign to me #gssoc24

**Comment by usha-madithati** [comment]
Yes sir I understand your concern. I will start working on it sir .

**Comment by Silentman87** [comment]
There is nothing in the learn.md file but I want to write something there so that the user can get details about the project.
please assign to me #gssoc24

**Comment by iamrudhresh** [comment]
Please assign this issue to me, under the GSSOC'24
