### ISSUE TITLE
Feat:Would like to Add a Signup and Login Page

### ISSUE THREAD

**Issue by sreehitha3** [usha-madithati/esmart.github.io#101]
### Describe the feature

The signup and login page will have sleek style.
When in future functionality is added we can actually store the data of users
Users can use smart saver from any device just by logging in.

### Add ScreenShots

![Screenshot_2024-05-14-10-08-37-08_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/usha-madithati/esmart.github.io/assets/146716148/556997cc-410d-4b28-a8fc-a99da50caf43)

This is the current UI with no signup login option I can add that

![329784335-2f744e4d-ef52-42a9-b2b5-553468d2164d](https://github.com/usha-madithati/esmart.github.io/assets/146716148/ae8417c7-8a26-423e-b182-627fb9b143ec)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by sreehitha3** [comment]
I raised an issues it's been so long when will be assigned to this??

**Comment by n14rishitha** [comment]
hi @usha-madithati 
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3
