### ISSUE TITLE
Navbar is unresponsive

### ISSUE THREAD

**Issue by KeshavPandia** [usha-madithati/esmart.github.io#102]
### Describe the feature

The navbar options like home, about, service etc. are unresponsive. I can resolve this issue and also redesign to make it look pleasing. Kindly assign me this issue under GSSOC'24.

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/97610764/7cd7e53d-97ce-463e-b83c-d7883a63697a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pulkit49** [comment]
I can help you with that. Please assign me under GSSOC 2024.
