### ISSUE TITLE
DOC: Hero Section

### ISSUE THREAD

**Issue by AditiPrabhakar** [usha-madithati/esmart.github.io#103]
### What's wrong with the existing documentation

The hero section is not displayed as the desired one. I can do the changes and work on the hero section for this website.
Please assign this to me.

### Add ScreenShots

![Screenshot (79)](https://github.com/usha-madithati/esmart.github.io/assets/139689410/30cd95d3-8ac7-4917-8427-37f976fa59be)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Justhomie** [comment]
I would like to work on this issue, please assign.
