### ISSUE TITLE
Feat : Improving the UI of the page 

### ISSUE THREAD

**Issue by sshivangi882** [usha-madithati/esmart.github.io#105]
### Describe the feature

The page does not have a proper navbar, and the main components of the pages are missing, I can create the whole UI from Scratch, using HTML, CSS, and JS

### Add ScreenShots

![Screenshot (879)](https://github.com/usha-madithati/esmart.github.io/assets/122531720/48b7d1b3-bc4a-450e-8dba-e6b7ab177d55)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nancyvaryani** [comment]
Hey, I can work on this, can you assign me the issue
