### ISSUE TITLE
Navbar design according to figma design

### ISSUE THREAD

**Issue by souravgope** [usha-madithati/esmart.github.io#106]
### Describe the feature

please assigm me i will work on it

### Add ScreenShots

i will make same as figma design

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by souravgope** [comment]
@kanikaa-3018  assign as soon as posible i will make the navbar same as figma design and further i will make all the pages

**Comment by kanikaa-3018** [comment]
means?

**Comment by souravgope** [comment]
i will make the navbar according to the figma design

**Comment by kanikaa-3018** [comment]
ok so how should i share the design? you can ask the owner, they have the design

**Comment by souravgope** [comment]
design is already in readme file of you repo

**Comment by souravgope** [comment]
@kanikaa-3018  please assign me

**Comment by yesaswiniswarna** [comment]
@kanikaa-3018 please assign me

**Comment by avikaagarwalll** [comment]
please assign me this task  I can do this

**Comment by Nikhilkumar111** [comment]
@kanikaa-3018 please assign me . I give my best to solve the issues .
