### ISSUE TITLE
[Enhancement] Adding a chatbot for better user navigation.

### ISSUE THREAD

**Issue by karishmaaa101** [usha-madithati/esmart.github.io#107]
### Describe the feature

Adding a chatbot would help the user go through the website and explore other additional features.

### Add ScreenShots

Similiar to this one:

![image](https://github.com/usha-madithati/esmart.github.io/assets/104766763/ad1d7087-9a2d-4b48-a72f-7f064353c29b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Choon38** [comment]
i want to work on this issue, please assign me @karishmaaa101

**Comment by karishmaaa101** [comment]
Hey, ask @usha-madithati for the same.

> I want to work on this issue, please assign me @karishmaaa101
