### ISSUE TITLE
Efficient backend developers who can design and maintain dynamic QR Scanner  and DB 

### ISSUE THREAD

**Issue by usha-madithati** [usha-madithati/esmart.github.io#114]
We need contributors who can design a dynamic QR scanner so that it helps us to keep users data dynamically. Actually, in our website we have a QR scanner. So whenever user scans a product QR through our QR scanner , the user should get the MFD and expiration date of the product , which they have scanned. So we need a dynamic QR scanner  in order to maintain that product details. Remember user may scan various grocery items so they are not static. 
       If any contributors know the work and are willing to contribute please do drop your contact details.
Thank You.

**Comment by avneetsingh154** [comment]
hi @usha-madithati I am willing to contribute .
 
 **my details -** 
 
 email- official.singh154@gmail.com
 mobile number - 8728893514
