### ISSUE TITLE
Design and setup DB for login page

### ISSUE THREAD

**Issue by usha-madithati** [usha-madithati/esmart.github.io#120]

**Comment by Deathnote45** [comment]
assign me this issue

**Comment by amitkumar2308** [comment]
Hey! I m Amit Can you assign me this issue

**Comment by 143divya** [comment]
Please assign me this issue

**Comment by sakshiSakshi77** [comment]
@usha-madithati , i would solve this by creating schema through MongoDB and would store user credentials . do assign me this issue please .

**Comment by usha-madithati** [comment]
> @usha-madithati , i would solve this by creating schema through MongoDB and would store user credentials . do assign me this issue please . 

Drop your whatsapp details
