### ISSUE TITLE
DOC: Enhance the content styling

### ISSUE THREAD

**Issue by syannam-12** [usha-madithati/esmart.github.io#129]
### What's wrong with the existing documentation

The style of the content and the font is too simple. I would like to style the page and enhance its appearance

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Akuu-27** [comment]
I agree to follow this project's Code of Conduct.I'm a GSSOC'24 contributor. I want to work on this issue. I'm interested to working on this issue.
