### ISSUE TITLE
Smooth Scroll Behavior

### ISSUE THREAD

**Issue by syannam-12** [usha-madithati/esmart.github.io#130]
### Describe the feature

Scroll behavior is not smooth and the page has overflow. I want to work on this issue. Please assign this task to me.

### Add ScreenShots

The scroll behavior of the website
![Uploading Screenshot (189).png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GauriGA** [comment]
@usha-madithati Could you please assign this issue to me under the GSSOC'24 label?
