### ISSUE TITLE
Feat: Addition of footer in web application

### ISSUE THREAD

**Issue by Ansh101112** [usha-madithati/esmart.github.io#131]
### Describe the feature

There is a need of footer in the application currently there is no footer and its make application incomplete. So please assign me this issue to add the footer for the application. @Durgesh-Vaigandla @usha-madithati 

### Add ScreenShots

![Screenshot (93)](https://github.com/usha-madithati/esmart.github.io/assets/87803348/f2796229-90e2-4211-b40d-a395b5b2901c)
See as of now no footer is present.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mehrun171** [comment]
i would like to work on this project...So, please assign me this task @usha-madithati @Durgesh-Vaigandla

**Comment by mehrun171** [comment]
Please add gssoc label
