### ISSUE TITLE
Feat: Add Search Box to the navbar

### ISSUE THREAD

**Issue by codewithishu** [usha-madithati/esmart.github.io#132]
### Describe the feature

Search box should be available at the right side of the navbar to improve the UI/UX 

### Add ScreenShots

![Screenshot 2024-05-19 001727](https://github.com/usha-madithati/esmart.github.io/assets/146975269/1929c574-6931-423b-af9f-e056f197f82b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by codewithishu** [comment]
@usha-madithati please label this and assign this to me

**Comment by pulkit49** [comment]
I can easily and effectively do this. Please assign me this task under GSSOC 2024.
