### ISSUE TITLE
BUG: Navabar is not responsive 

### ISSUE THREAD

**Issue by meetarora10** [usha-madithati/esmart.github.io#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The present navbar is not responsive . Assign this task to me and I will create a completely responsive navbar suitable for all kinds of devices.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjanhaa-yenugu** [comment]
Hello @usha-madithati , please label this issue. I am interested in working on this issue. I have previously developed a responsive landing page for a travel website. I am confident that I can use my skill to create a responsive navbar. I am available for further discussion if needed. Thank you.

**Comment by pulkit49** [comment]
I can help you create Responsive Navbar.

**Comment by aasthabagrawal** [comment]
Plz assign this task to me
