### ISSUE TITLE
Need efficient backend developers 

### ISSUE THREAD

**Issue by usha-madithati** [usha-madithati/esmart.github.io#136]
Contact us ASAP. Drop your whatsap details.

**Comment by kritikaapathak** [comment]
I can contribute to this as a backend developer .

**Comment by usha-madithati** [comment]
> I can contribute to this as a backend developer . 

Drop your whatsapp details

**Comment by kritikaapathak** [comment]
> > I can contribute to this as a backend developer .
> 
> Drop your whatsapp details

Whatsapp - 9759073787

**Comment by kritikaapathak** [comment]
Ping me on LinkedIn !
www.linkedin.com/in/kritika-pathak12
