### ISSUE TITLE
Feat:Adding Testimonials 

### ISSUE THREAD

**Issue by sharmi4590** [usha-madithati/esmart.github.io#139]
### Describe the feature

Hey @usha-madithati 
Adding testimonials which is placed above the footer , always makes user experience much better and user always searches for reviews before use . So a pleasant testimonials will make the website much better.It will make the users to believe in the website as well. I will make sure the testimonials match your UI design.It declines tre trust issues of the users.

### Use Case

This is my previous work regarding testimonials.
On placing cursor on each testimonial will flip it and show the review.

### Benefits

The user will get to know how many people got benefited from the website.

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/102676949/8097dad3-777c-4020-b77f-a6e1ce655a03)
![image](https://github.com/usha-madithati/esmart.github.io/assets/102676949/3135c170-aa16-40ad-b815-e026431313f2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Akuu-27** [comment]
I agree to follow this project's Code of Conduct
I'm a GSSOC'24 contributor
I want to work on this issue
