### ISSUE TITLE
Enhancement: Add animations to landing page

### ISSUE THREAD

**Issue by sau-mili** [usha-madithati/esmart.github.io#140]
Add animation to texts and images like,
the section that comes after Manage your inventory

NB: I am a gssoc contributor

**Comment by GauriGA** [comment]
@usha-madithati Could you please assign this issue to me under the GSSOC'24 label?

**Comment by AkshayaSiripuram** [comment]
I would like to work on this project, Please assign it to me.
/assign

**Comment by gopuswathi18** [comment]
I would like to work on this project. Please assign it to me.
/assign
