### ISSUE TITLE
BUG: Browser Image Button 

### ISSUE THREAD

**Issue by theeayushkumar** [usha-madithati/esmart.github.io#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Browser Image Button  is not working 
![image](https://github.com/usha-madithati/esmart.github.io/assets/128235540/e36759c0-b9a2-4838-a1ae-82f009b1e050)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ankit389** [comment]
add  Browser Image Button  , #143
i can fix this problem
