### ISSUE TITLE
Feat: Add "Back to Top" Button on Homepage

### ISSUE THREAD

**Issue by AsmitaMishra24** [usha-madithati/esmart.github.io#145]
### Describe the feature

The addition of a "Back to Top" button on the homepage of our website would enhance user experience by providing a convenient way for users to quickly return to the top of the page after scrolling down. This feature is commonly seen on many websites and has become an expected element for smooth navigation.

### Add ScreenShots

![Screenshot 2024-05-21 012940](https://github.com/usha-madithati/esmart.github.io/assets/146121869/b2297297-184c-4a61-b303-42c1894856d8)
![Screenshot 2024-05-21 013007](https://github.com/usha-madithati/esmart.github.io/assets/146121869/b7b10ef3-911a-4da0-a4f0-d13343378128)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ujjwalkumar-64** [comment]
i want to work on this issue as a part of gssoc'24

**Comment by AsmitaMishra24** [comment]
But, I have raised the issue so it should be first assigned to me.

**Comment by AsmitaMishra24** [comment]
@usha-madithati, Kindly assign me to address this particular issue. I am prepared to help solve it.
