### ISSUE TITLE
Feat:add background and hover effect in working guide page 

### ISSUE THREAD

**Issue by Prakrati1907** [usha-madithati/esmart.github.io#146]
### Describe the feature

will add on background effects to make the process of working look more readable and attractive.
@usha-madithati please assign it to me

### Add ScreenShots

![Screenshot 2024-05-21 015549](https://github.com/usha-madithati/esmart.github.io/assets/120261907/9919e6ff-8478-493c-b442-b8f4bed9aa26)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Akuu-27** [comment]
I agree to follow this project's Code of Conduct
I'm a GSSOC'24 contributor
I want to work on this issue

**Comment by Chandni-2022** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue
