### ISSUE TITLE
Readme.md Update_DOC:

### ISSUE THREAD

**Issue by Meetjain1** [usha-madithati/esmart.github.io#152]
### What's wrong with the existing documentation

Currently Our readme.md file is not looking good 
It is looking like a learn.md file I would suggest to @usha-madithati assign me this issue I will create a fully new version of readme file , have created the same in many repository , I am working under gssoc

changes required are missing video of our project , allignment of text , open source section , contributors section , code of conduct, license section , features section and many more I will create a beautiful attracting readme file . 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Karthik5400** [comment]
What's wrong with the existing documentation
Currently Our readme.md file is not looking good
It is looking like a learn.md file I would suggest to @usha-madithati assign me this issue I will create a fully new version of readme file , have created the same in many repository , I am working under gssoc

changes required are missing video of our project , allignment of text , open source section , contributors section , code of conduct, license section , features section and many more I will create a beautiful attracting readme file .
