### ISSUE TITLE
DARKMODE_Feat:

### ISSUE THREAD

**Issue by Meetjain1** [usha-madithati/esmart.github.io#155]
### Describe the feature

we can add darkmode feature to our current website to provide better user friendly experience

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/133582566/beaa2664-cc2d-476e-b0b1-14c95fb3d030)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GauriGA** [comment]
@usha-madithati Could you please assign this issue to me under the GSSOC'24 label?
