### ISSUE TITLE
jump to top-button_Feat:

### ISSUE THREAD

**Issue by Meetjain1** [usha-madithati/esmart.github.io#156]
### Describe the feature

we can add a jump to top button in our current website , to provide better user friendly experience .

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/133582566/015a40f6-d760-4971-b60a-11ba7c07499c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ved8290** [comment]
I want to work on this issue
