### ISSUE TITLE
BUG:validation issue in login form/page

### ISSUE THREAD

**Issue by Srujitha-Raghava** [usha-madithati/esmart.github.io#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-25 115033](https://github.com/usha-madithati/esmart.github.io/assets/143430142/23e2ed8f-a3c5-47bd-b3f6-952e1d823c83)

Here the phonenumber is accepting any no.of digits and i want to add validation so that only a 10 digited phonenumber is accepted.
@usha-madithati I want to work on this issue oonce you assign me this under GSSOC.Thankyouuu!!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Srujitha-Raghava** [comment]
@Durgesh-Vaigandla @usha-madithati ??

**Comment by Srujitha-Raghava** [comment]
@Durgesh-Vaigandla the labels should be "gssoc" and "level1" i guess. will you change them in the merged PR,also!! Thankyou!

**Comment by Durgesh-Vaigandla** [comment]
@Srujitha-Raghava I'm not the right person who have the access for it I have some level of permissions to this repo. 
@usha-madithati kindly look into the issue

**Comment by usha-madithati** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### What happened?
> 
> ![Screenshot 2024-05-25 115033](https://github.com/usha-madithati/esmart.github.io/assets/143430142/23e2ed8f-a3c5-47bd-b3f6-952e1d823c83)
> 
> Here the phonenumber is accepting any no.of digits and i want to add validation so that only a 10 digited phonenumber is accepted.
> @usha-madithati I want to work on this issue oonce you assign me this under GSSOC.Thankyouuu!!
> 
> ### Record
> 
> - [X] I agree to follow this project's Code of Conduct
> - [X] I'm a GSSOC'24 contributor
> - [X] I want to work on this issue

Ok you can start working on this issue we will assign you @Srujitha-Raghava

**Comment by Srujitha-Raghava** [comment]
@usha-madithati mam this issue is solved,but the problem is about the lables 
  1.  gssoc
  2.  level1
  This is how the labels should be, I am requesting you to change these!

**Comment by usha-madithati** [comment]
> @usha-madithati mam this issue is solved,but the problem is about the lables 
>   1.  gssoc
>   2.  level1
>   This is how the labels should be, I am requesting you to change these!

We will check and change that . Thank you @Srujitha-Raghava
