### ISSUE TITLE
BUG: NO BACKEND LOGIC IN THE PROJECT

### ISSUE THREAD

**Issue by MuthuvelA** [usha-madithati/esmart.github.io#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is no backend logic for the project including login and signup page. I would like to work in this issue writing the backend logic for login and signup page using jwt token for secure handling of data. I have prior experience of working in backend logics with efficient MVC architecture. So @usha-madithati please assign this issue to me under labels gssoc24 and level 2 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ansh101112** [comment]
Please review the code again friend. And see the code of backend in MVC category.
