### ISSUE TITLE
Feat: Add inputs Labels in contact us page

### ISSUE THREAD

**Issue by SrinivasDevolper** [usha-madithati/esmart.github.io#210]
### Describe the feature

when the user clicks the send message button on the Contact Us page then should show the text labels as a warning

### Add ScreenShots

https://github.com/usha-madithati/esmart.github.io/assets/121508628/b7f2b96e-c8f8-45a3-a955-12e94d1c904f

![contact us image](https://github.com/usha-madithati/esmart.github.io/assets/121508628/f4d57874-98be-42dc-b9df-3eb4bb9ae06f)

**I am GSSOC24 Contributor
please assign me, I would like to work on it**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Soujanya2004** [comment]
hello @usha-madithati can you assign me this issue, I have been following your project and would love to help fix this issue under gssoc.
