### ISSUE TITLE
[Feature] : Implement Dark & Light mode

### ISSUE THREAD

**Issue by sivaprasath2004** [usha-madithati/esmart.github.io#217]
### Describe the feature

- In this project Not availble for the `Dark & Light` mode.
- I will ready work on this project .
- please assign me ...
- i will ready to work on it..

### Add ScreenShots

[Screencast from 2024-06-05 20-47-22.webm](https://github.com/usha-madithati/esmart.github.io/assets/121082414/ff5732c9-4760-419b-805a-3c8a9fbc0c0b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Soujanya2004** [comment]
hello @usha-madithati can you assign me this issue, I have been following your project and would love to help fix this issue under gssoc.
