### ISSUE TITLE
improve header and footer 

### ISSUE THREAD

**Issue by Silentman87** [usha-madithati/esmart.github.io#224]
### Describe the feature

inside navbar button placed normally i want to make changes 
1. by adding colour 
2. by adding background colour
3. by adding shawdow on button and also add mouse curser click feature
also i want to improve footer by changing font size and font family 
please assign me this issue..

### Add ScreenShots

![Uploading Screenshot 2024-06-06 092441.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Silentman87** [comment]
please assign me this isuue...

**Comment by Soujanya2004** [comment]
hello @usha-madithati can you assign me this issue, I have been following your project and would love to help fix this issue under gssoc.
