### ISSUE TITLE
Enhancing contact us page

### ISSUE THREAD

**Issue by ananyag309** [usha-madithati/esmart.github.io#227]
### What's wrong with the existing documentation

As soon as we submit response on the page the form gets reset. It will be a good practice if we drop a confirmation message before reseting the form. @usha-madithati ma'am please assign this issue to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Soujanya2004** [comment]
hello @usha-madithati can you assign me this issue, I have been following your project and would love to help fix this issue under gssoc.
