### ISSUE TITLE
Recreating Navbar 

### ISSUE THREAD

**Issue by supriyagaut** [usha-madithati/esmart.github.io#256]
![Screenshot 2024-06-10 124346](https://github.com/usha-madithati/esmart.github.io/assets/141560711/29f69d0f-d32f-4383-afe3-a18449b6a359)
@usha-madithati I want to recreate the navbar it would be more attractive and user friendly.
kindly assign me the issue under GSSOC' 24.

**Comment by safiya2610** [comment]
Please assign it to me and label this issue under GSSOC'24, I would like to work on this issue.

**Comment by Soujanya2004** [comment]
hello @usha-madithati can you assign me this issue, I have been following your project and would love to help fix this issue under gssoc.
