### ISSUE TITLE
Convert to React code

### ISSUE THREAD

**Issue by Sudhan22z265** [usha-madithati/esmart.github.io#26]
### Describe the feature

Converting react code helps to add backend and more UI related options

### Add ScreenShots

Assign me this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nakshatravyas** [comment]
Hey, I want to contribute to this project as a part of GSSOC 2024. I am a MERN stack developer and I have worked on several projects and won hackathons as well. I can convert code to reactjs. 

Here's my linkedin profile : https://www.linkedin.com/in/nakshatravyas/
Github profile : https://github.com/nakshatravyas

**Comment by parth3083** [comment]
Hey, I am a frontend developer who creates stunning and modern websites.
I completed the internship as a frontend developer.
I create websites with HTML, CSS, JS, and React, and I use JS libraries for animation and smooth scrolling.
The following are the works where I used lgsap animation and locomotive js : 
https://exoape-clone-parth.netlify.app/
https://ochi-clone-parth.netlify.app/

**Comment by usha-madithati** [comment]
Heyy!! @parth3083 nice to meet you. please do share your contact details , as we do have another UI designer contribuiting for our project. So please do  share your whatsap contact. so that i can contact you.

**Comment by parth3083** [comment]
This is my whatsapp number : 7383930395

**Comment by nakshatravyas** [comment]
Hey, I can convert the code into reactjs. I am a MERN stack developer and i have worked on several projects.

Here is live link of some projects: 
https://hungertimee.netlify.app/
https://nakshatravyas.netlify.app/
https://drive.google.com/file/d/1A78gjCG4u54g3EbyGCS46CNPyKTVfOw5/view?usp=sharing
https://quizzy-quizapp.netlify.app/

**Comment by Ansh101112** [comment]
I want to work on this issue @usha-madithati assign me this issue and add badge and levels of difficulty to it.
