### ISSUE TITLE
Feat: Add a "Remember ME" Button for LOGIN

### ISSUE THREAD

**Issue by codercake** [usha-madithati/esmart.github.io#268]
### Describe the feature

The "Remember Me" feature in login systems allows users to opt for persistent authentication, so they don't have to enter their credentials every time they access a website or application. It would be pretty useful for individuals who are regular users. 

### Add ScreenShots

![Screenshot 2024-06-12 165322](https://github.com/usha-madithati/esmart.github.io/assets/117517206/a2cc7f35-ef76-47d7-a619-dd5c6eb5a5e4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Soujanya2004** [comment]
hello @usha-madithati can you assign me this issue, I would love to help fix this issue under gssoc.
