### ISSUE TITLE
Review section along with quality and placement of images

### ISSUE THREAD

**Issue by kanikaa-3018** [usha-madithati/esmart.github.io#27]
there is no customer review section, please assign this issue to me for GSSoc'24, ill include a review section along with a QNA for the users

**Comment by usha-madithati** [comment]
That's a good idea @kanikaa . can you share your Whatsapp details. Because I want you to have a conversation with our project UI designer, so that you can proceed with your work.
please do reply ASAP.

**Comment by usha-madithati** [comment]
@kanikaa-3018 please do reply of you are not responding to our messages iam worried that I can't assign that issue to you

**Comment by kanikaa-3018** [comment]
yes maam, sorry for late reply, ill share the details to u personally on your email id

**Comment by kanikaa-3018** [comment]
@usha-madithati can you please share your email id

**Comment by usha-madithati** [comment]
> @usha-madithati can you please share your email id

ushamadithati712@gmail.com
