### ISSUE TITLE
Feature: Addition of background image

### ISSUE THREAD

**Issue by DhayanandhS** [usha-madithati/esmart.github.io#270]
### Describe the feature

As  we can see in the [https://esmart-github-io.vercel.app/user/login](login) page, it looks so empty and simple. 

So I would like to change the layout or design of the plain background in login page. 

Can you assign me for this issue I can start working on it. 

### Add ScreenShots

![Screenshot 2024-06-12 233955](https://github.com/usha-madithati/esmart.github.io/assets/112493275/14f525c7-3fa8-41e2-aa35-64d7a6acd093)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SheetalDawar** [comment]
i would like to work on this project, please assign this to me

**Comment by Soujanya2004** [comment]
hello @usha-madithati can you assign me this issue, I would love to help fix this issue under gssoc.
