### ISSUE TITLE
Feat:Adding Google Auth

### ISSUE THREAD

**Issue by mukilan2815** [usha-madithati/esmart.github.io#271]
### Describe the feature

We can add google auth so that user can login within one click and it will make user exp better.

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/71129858/e7975042-587f-4a1c-987f-172c12fe7134)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Soujanya2004** [comment]
hello @usha-madithati can you assign me this issue, I would love to help fix this issue under gssoc.
