### ISSUE TITLE
Add Icons to Navbar

### ISSUE THREAD

**Issue by sailaja-adapa** [usha-madithati/esmart.github.io#273]
### Describe the feature

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add icons to navbar items it will make our website to look Attractive 

Can you please assign me this issue under gssoc'24

### Add ScreenShots

![icons](https://github.com/usha-madithati/esmart.github.io/assets/161804629/10aa12ee-d1a4-4880-8d98-243897db47fd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DhruvJohri** [comment]
please assign this issue to me @usha-madithati under gssoc24

**Comment by Soujanya2004** [comment]
hello @usha-madithati can you assign me this issue, I would love to help fix this issue under gssoc.
