### ISSUE TITLE
Adding hover effects and more information to about section of website

### ISSUE THREAD

**Issue by sahithinandikula** [usha-madithati/esmart.github.io#276]
### Describe the feature

The About section of the website has less information describing the services provided by the website, also it can be enhanced by adding hover effects or animations to the images. This makes the user interactivity more easy and better.

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/138794574/192a3a8e-389e-4c03-ad5f-19ef49300cf3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Soujanya2004** [comment]
hello @usha-madithati can you assign me this issue, I would love to help fix this issue under gssoc.
