### ISSUE TITLE
Add visibility for password

### ISSUE THREAD

**Issue by AkhilaSunesh** [usha-madithati/esmart.github.io#281]
### Describe the feature

Location : signin and sign up forms
Users can view the password when prompted.

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/140897461/498efc7b-6ab4-473a-bfd1-3d521cbdd102)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Soujanya2004** [comment]
hello @usha-madithati can you assign me this issue, I would love to help fix this issue under gssoc.
