### ISSUE TITLE
Design an efficient QR code for scanning each and every product of user's.

### ISSUE THREAD

**Issue by usha-madithati** [usha-madithati/esmart.github.io#3]

**Comment by bhavanishanker-png** [comment]
I would like to work on this project, please assign this to me

**Comment by usha-madithati** [comment]
kindly drop your linked in details. stay tuned. we will contact you shortly. please do share your linked in details.

**Comment by bhavanishanker-png** [comment]
[www.linkedin.com/in/bhavani-shankar-49a4b228b](url)

**Comment by bhavanishanker-png** [comment]
[https://www.linkedin.com/in/bhavani-shanker-49a4b228b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app](url)

**Comment by rajsingh19** [comment]
i would like to work on this project , please assign me

**Comment by anushkaaa34** [comment]
Would like to contribute to this . Here's my LinkedIn profile 
https://www.linkedin.com/in/anushka-sinha-09606b267/
Please assign me this issue

**Comment by gitsofaryan** [comment]
Hi can you please assign me this work 
https://www.linkedin.com/in/aryan-jain07/

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
@usha-madithati Mam, Plz can you assign this issue.
Here is my LinkedIn ID, which I mentioned:
https://www.linkedin.com/in/pratik-chavan-910764211/

**Comment by cpratik1307** [comment]
I am grateful to @usha-madithati Mam for providing me with this chance.

**Comment by usha-madithati** [comment]
> I am grateful to @usha-madithati Mam for providing me with this chance
Welcome to our project @cpratik1307 .
Can you please share your whatsapp details .please share asap .
Thank you

**Comment by cpratik1307** [comment]
> > I am grateful to @usha-madithati Mam for providing me with this chance
> > Welcome to our project @cpratik1307 .
> > Can you please share your whatsapp details .please share asap .
> > Thank you

Yes, this is my WhatsApp number: 8329389682.

**Comment by anushkaaa34** [comment]
Thank you @usha-madithati  for providing me this chance

**Comment by usha-madithati** [comment]
> Thank you @usha-madithati  for providing me this chance

Please do share your whatsapp details
