### ISSUE TITLE
Feat: Back to top button

### ISSUE THREAD

**Issue by Aditi-P22** [usha-madithati/esmart.github.io#31]
### Describe the feature

This feature proposes the addition of a "Back to Top" button functionality to enhance user experience in navigating through lengthy pages within the project. The "Back to Top" button would allow users to swiftly return to the beginning of the page, offering convenience and improved usability.

The proposed solution involves implementing a visually discreet yet easily accessible button, positioned at the bottom right corner of the viewport. Upon clicking or tapping, the button smoothly scrolls the page back to the top, providing a seamless navigation experience. The button's design will align with the project's aesthetic principles while maintaining clarity and functionality.

### Add ScreenShots

<img width="959" alt="GSSoc 1" src="https://github.com/usha-madithati/esmart.github.io/assets/106650588/183295a9-7523-400f-8f0e-a9879a98cfca">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aditi-P22** [comment]
Please assign this issue to me under GSSoC'24

**Comment by Nitin8426** [comment]
Describe the feature
"Back to Top" button , when clicked, scroll the page instantly to the very top,  letting user quickly navigate long webpages. They're often added by website creators to improve user experience, especially on pages with a lot of content.

Screenshot
![fotor-202405112570](https://github.com/usha-madithati/esmart.github.io/assets/164453064/66b39585-5de3-4218-a1d2-ea35f26bb23e)

Please assign this issue to me.

**Comment by JanitKumar** [comment]
please assign this issue to me

**Comment by shrashti2004** [comment]
Hi , Assign this issue to me ,under GSSOC24

**Comment by Aleena-Memon** [comment]
please Assign this issue to me under GSSOC24
