### ISSUE TITLE
Feat: Improving header UI

### ISSUE THREAD

**Issue by Aditi-P22** [usha-madithati/esmart.github.io#32]
### Describe the feature

Issue Description
The current header UI in our project serves its purpose well, but we believe it can be further improved to provide a more intuitive and visually appealing experience for our users. This issue aims to solicit ideas, designs, and implementations to revamp the header UI.

Objective
The primary objective of this issue is to enhance the header UI to make it more user-friendly, aesthetically pleasing, and accessible across various devices and screen sizes.

### Add ScreenShots

<img width="959" alt="GSSoc 1" src="https://github.com/usha-madithati/esmart.github.io/assets/106650588/e2011c8b-f61e-44d5-8acf-08a42d12c551">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aditi-P22** [comment]
Please assign this issue to me under GSSoC'24

**Comment by Gokilp** [comment]
please asssign to me

**Comment by drashtiv03** [comment]
Please assign me this issue under GSSoC'24.
