### ISSUE TITLE
BUG: Very Close Content

### ISSUE THREAD

**Issue by theeayushkumar** [usha-madithati/esmart.github.io#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Text close

![image](https://github.com/usha-madithati/esmart.github.io/assets/128235540/1ab3d47c-59bd-4360-b94f-0dbd9d367f2b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by usha-madithati** [comment]
@theeayushkumar thanks for recognising it. Drop your contact details I will let you deal with that issue

**Comment by theeayushkumar** [comment]
> @theeayushkumar thanks for recognising it. Drop your contact details I will let you deal with that issue

Email id-ayush.kumar20031999@gmail.com
