### ISSUE TITLE
Feat: Zod validation for login signup

### ISSUE THREAD

**Issue by RahulK4102** [usha-madithati/esmart.github.io#329]
### Describe the feature

using zod validation it will validate if the form data is correct or not

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/119075798/856f9c3a-b515-44e7-89a3-48cb7a2b47fd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asin-Junior-Honore** [comment]
Hey @RahulK4102,

If you need a second hand to complete and fix this issue once it gets assigned to you, I'll be happy to help!
