### ISSUE TITLE
Feat: Adding footer

### ISSUE THREAD

**Issue by Aditi-P22** [usha-madithati/esmart.github.io#33]
### Describe the feature

The goal of this feature request is to implement a footer across all pages of our project repository. The footer should include essential links, such as the project's home, about us, documentation and relevant social media channels.
The footer adopts a clean and minimalistic design to maintain consistency with the project's overall aesthetic.
It utilizes contrasting colors and clear typography for improved readability and accessibility.
The layout is responsive, ensuring optimal viewing and interaction across various devices and screen sizes.

### Add ScreenShots

<img width="959" alt="GSSoc 1" src="https://github.com/usha-madithati/esmart.github.io/assets/106650588/19f244cd-119c-439b-ae8c-a2366b456fd1">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aditi-P22** [comment]
Please assign this issue to me under GSSoC'24

**Comment by Nitin8426** [comment]
The aim of this feature request is to implement a footer across all pages of our project repository. The footer also include 
1. Essential Quick links, such as the project's home, about us, services, contact and Review. 
2. Links that  help user navigate through his profile with options as  view Profile, view Products,, View Alarm, Set alarm. 
3. An additional mail option for providing email Address and reach out quickly to resolve Problems.
 Screenshot
![Screenshot 2024-05-11 023254](https://github.com/usha-madithati/esmart.github.io/assets/164453064/b6b543c3-2d34-48e0-8ee2-30b5a0682b6f)

The footer adopts a clean and minimalistic design to maintain consistency with the project's overall aesthetic.
It utilizes contrasting colors and clear typography for improved readability and accessibility.
The layout is responsive, ensuring optimal viewing and interaction across various devices and screen sizes.

please assign me this issue.

**Comment by drashtiv03** [comment]
Please assign me this issue under the label GSSoC'24.

**Comment by Nih1tGupta** [comment]
Hi ,I'm Nihit from NIT Raipur, As a GSSOC'24 contributor please assign this issue to me .

**Comment by harshitpnd12** [comment]
Please assign this issue

**Comment by Anou25** [comment]
Hi, I want to work on this issue please assign it to m

**Comment by Srujitha-Raghava** [comment]
hey @usha-madithati Adding a footer to the webpage has been a significant enhancement suggestion, and I'm excited to contribute to its implementation.
I've worked on incorporating a footer section to the existing webpage. The footer includes essential information such as contact details, copyright information, and links to relevant resources. Additionally, I've ensured that the footer design aligns with the overall branding and style of the webpage for a cohesive user experience.
please assign me this under gssoc

**Comment by n14rishitha** [comment]
Hi @usha-madithati 
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3
