### ISSUE TITLE
🌟 Feature: Add a Scroll "Progress Bar"

### ISSUE THREAD

**Issue by aslams2020** [usha-madithati/esmart.github.io#331]
### Describe the feature

Hey @usha-madithati,
I want to add a **"Scroll Down Progress Bar"**

This feature adds a scroll down progress bar to the website, which visually indicates the user's progress as they scroll down the page. The progress bar enhances user experience by providing a clear visual cue of their location on the page and how much content remains to be viewed.

**Expected Outcome**
The scroll down progress bar will provide users with a better understanding of their position on the page, enhancing navigation and overall user experience.

### Add ScreenShots

Example Like this - 

![WhatsApp Image 2024-06-23 at 00 03 04_03f80295](https://github.com/Anushkabh/krishiconnect/assets/131389695/778dce80-b90f-4ef7-931e-06f1622cb6b1)

Could you please assign me this issue under GSSOC'24?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by usha-madithati** [comment]
Drop your contact details @aslams2020

**Comment by aslams2020** [comment]
Sure https://www.linkedin.com/in/aslamsayyad02/

**Comment by aslams2020** [comment]
@usha-madithati

**Comment by usha-madithati** [comment]
Yeah I will assign you

**Comment by aslams2020** [comment]
@usha-madithati

**Comment by usha-madithati** [comment]
I have tried contacting through your linkedin. But there is no response that's why iam waiting whether you are there are not .

**Comment by usha-madithati** [comment]
@aslams2020 I have assigned you. Make sure you develop according to our home page details. Please do stay in contact so that i can know your work progress.

**Comment by aslams2020** [comment]
> @aslams2020 I have assigned you. Make sure you develop according to our home page details. Please do stay in contact so that i can know your work progress. 

SURE @usha-madithati
