### ISSUE TITLE
BUG:Headers needs to be aligned in center

### ISSUE THREAD

**Issue by kapilG0** [usha-madithati/esmart.github.io#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot_20240625_230156](https://github.com/usha-madithati/esmart.github.io/assets/59639410/70c674d5-f85f-48cb-8b77-6533ff8d43e0)
In mobile view it. Needs to align properly 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @usha-madithati please assign this issue to me under gssoc 24

**Comment by usha-madithati** [comment]
> Hello @usha-madithati please assign this issue to me under gssoc 24 

We are developing for desktop so please do set your mobile chrome to desktop site , you will not have that issue

**Comment by kapilG0** [comment]
> > Hello @usha-madithati please assign this issue to me under gssoc 24
> 
> We are developing for desktop so please do set your mobile chrome to desktop site , you will not have that issue

Ok
