### ISSUE TITLE
Needs to delete a content in admin dashboard 

### ISSUE THREAD

**Issue by usha-madithati** [usha-madithati/esmart.github.io#345]
As it's irrelevant to our website I want them to be removed.
The admin dashboard consists of a graph which shows growth and income of website .   We want that to be removed as we are developing a free website .

**Comment by Ansh101112** [comment]
Please assign me this issue as I have recently built the admin dashboard and know the key points where and what is not aligning with the website theme. Please do assign me this issue @usha-madithati
