### ISSUE TITLE
Feat: add footer to login and contact us pages

### ISSUE THREAD

**Issue by AbhishiktaRay03** [usha-madithati/esmart.github.io#346]
### Describe the feature

footer should be visible on every page

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/127621443/0c6397aa-36f1-4ca1-8728-44348c5db370)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AadiJain06** [comment]
Assign me this issue i can work on it
