### ISSUE TITLE
DOC: Enhancing the About Section

### ISSUE THREAD

**Issue by nsk6704** [usha-madithati/esmart.github.io#35]
### What's wrong with the existing documentation

While there's nothing that is glaring out, it would be wonderful for users to understand the know-hows of the website in a better and structured manner.

The current about section is written in a single long(relatively)  paragraph which makes it difficult for potential users.

By organising the information and adding a bit more context, users checking the documentation would be greatly benefitted!

I hence kindly request you to assign this issue to me, an aspiring web developer certified by freeCodeCamp in Web Design and have also interned at a company named Codsoft.

Here is my LinkedIn Profile for more information!

https://www.linkedin.com/in/saketh-kashyap-nagendra/

### Add ScreenShots

![Screenshot_20240511_074056_Chrome](https://github.com/usha-madithati/esmart.github.io/assets/117816770/acb246da-5822-4878-aa93-083152e5e418)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
Can you please assign this issue to me

**Comment by shruti110503** [comment]
@usha-madithati I want to work on this issue. Please assign this issue to me. Here's my linkdln profile-
 https://www.linkedin.com/in/shruti-shukla-9aa944251/

**Comment by Rishabh001pawar** [comment]
I am contributer , can youi assign me this issue
