### ISSUE TITLE
Feature🌟: Create All Dedicated Pages For "LEGAL" Section Of Footer

### ISSUE THREAD

**Issue by aslams2020** [usha-madithati/esmart.github.io#379]
### Describe the feature

Hey @usha-madithati,

I'd like to propose an enhancement for the website's footer "Legal Information" section.
Currently, **there are unlinked texts** like **"Privacy Policy" , "Terms of Service", "", "Disclaimer" and "Cookies Policy"** without dedicated pages.

### I propose to:
1. Create Dedicated Pages **for Each** Links **"Privacy Policy" , "Terms of Service", "Disclaimer" and "Cookies Policy"** 
2. **Styling Each page** to **follow the Main Theme** of the website.
3. **Adding Navigating Links** to them to go to respective pages.
4. Each page will provide **detailed information** about the respective **service, its benefits, and how members can engage.**

![image](https://github.com/usha-madithati/esmart.github.io/assets/131389695/48dcd664-8ea8-42ce-a8be-7e9e863d1777)

This enhancement will not only improve navigation but also enrich Smart Saver's interaction by offering more comprehensive insights into Legal Section.

Please Assign me this Issue Under GSSoC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by usha-madithati** [comment]
I have already assigned that whole footer link activation to some other contributor
