### ISSUE TITLE
Feat: Adding some videos, articles or guides on smart strategies, planning or other tips to save money.

### ISSUE THREAD

**Issue by Chelseasingla1** [usha-madithati/esmart.github.io#38]
### Describe the feature

I would like to add a features where users can enjoy videos or articles on how to save money on buying groceries basically we will be providing tips and tricks to them , how to do proper planning, how to do meal planning, how to create lists, how to shop on budge. Or like by using coupons.

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/129886894/be94b0eb-a5ef-4fbb-9da8-987a61e62ae7)
I am not able to provide proper picture of this but would like to work on it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Chelseasingla1** [comment]
Please assign me this issue under GSSoC'24

**Comment by Chelseasingla1** [comment]
Here is my LinkedIn profile like: https://www.linkedin.com/in/chelsea-singla-57ab092a0/

**Comment by JanitKumar** [comment]
please assign this issue to me
