### ISSUE TITLE
Enhancing the UI of Select items page

### ISSUE THREAD

**Issue by jashanp2005** [usha-madithati/esmart.github.io#39]
### Describe the feature

The current UI of the grocery selection form could benefit from enhancements to improve user experience and visual appeal. By making these improvements, we can create a more engaging and user-friendly interface for selecting grocery items. This will ultimately lead to a better overall experience for users interacting with the application.

Proposed changes 

- CSS Refinement: Update the CSS styles to improve readability, visual consistency, and alignment of elements.

- Typography Enhancement: Adjust font sizes, styles, and colors for better legibility and aesthetic appeal.

- Button Styling: Refine the styling of the submit button to make it more visually appealing and intuitive for users.

- Background Image: Consider updating the background image or adjusting its properties to better complement the overall design of the form.

- Accessibility Considerations: Ensure that the UI changes maintain or improve accessibility for all users, including those with disabilities.

I'm eager to contribute to this improvement and am willing to take ownership of implementing these changes. Please assign me this issue.

### Add ScreenShots

This is a demo version of just how much the UI can be improved, please assign me this issue.

![Screenshot (659)](https://github.com/usha-madithati/esmart.github.io/assets/160238258/6e9b10eb-46b6-49a0-b5bd-1c82ee92f462)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Chelseasingla1** [comment]
Here is my LinkedIn profile like: https://www.linkedin.com/in/chelsea-singla-57ab092a0/

**Comment by its-kritika** [comment]
I can add and improvise the select items page to make it more visually attractive and user friendly. You can visit my linkedIn profile : https://www.linkedin.com/in/kritika-kesarwani-034104239/
