### ISSUE TITLE
Feat: Mobile nav bar

### ISSUE THREAD

**Issue by Saipradyumnagoud** [usha-madithati/esmart.github.io#392]
### Describe the feature

Adding nav bar which can be assed in the mobile

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/143107589/0c77f146-ddb3-47b5-99e8-dc3846520381)

You can see that for small screen displays  the nav bar is not so responsive

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saipradyumnagoud** [comment]
@usha-madithati  Please assign me the issue

**Comment by usha-madithati** [comment]
@Saipradyumnagoud I will assign you

**Comment by Saipradyumnagoud** [comment]
> @Saipradyumnagoud I will assign you

Yes Thank you..
