### ISSUE TITLE
Provide an efficient way of getting notifications regarding expiration date of user's products. 

### ISSUE THREAD

**Issue by usha-madithati** [usha-madithati/esmart.github.io#4]

**Comment by usha-madithati** [comment]
Iam happy that people are coming forward to work on this project. I will
talk with project manager and get back to you as soon as possible.
Thank you

**Comment by usha-madithati** [comment]
Hi. I hope you this message reaches you. If you are still intrested in contributing to our project. Kindly share your linked in profile

**Comment by bhavanishanker-png** [comment]
[www.linkedin.com/in/bhavani-shankar-49a4b228b](url)

**Comment by usha-madithati** [comment]
Please do check the link you have shared now . Check it out and let me know

**Comment by bhavanishanker-png** [comment]
[https://www.linkedin.com/in/bhavani-shanker-49a4b228b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app](url)

**Comment by Gokilp** [comment]
please assign to me #gssoc24

**Comment by usha-madithati** [comment]
@Gokilp can you share your linked in profile

**Comment by Gokilp** [comment]
https://www.linkedin.com/in/gokilp/

**Comment by usha-madithati** [comment]
Ok I will assign that issue to you . Since you needs to develop the entire
UI by yourself , I would suggest to work with someone . I already have
selected a person for that . So if you are ok with working along with him I
will take you in.
Kindly share your reply .
Thank you.

**Comment by Gokilp** [comment]
okie mam

**Comment by usha-madithati** [comment]
Heyy!! Hi @Gokilp are you efficient in sending the nofications from our website to user's. I do wants to know your ability in prior. so please do reply ASAP. Share your reply so that i can assign the task to you.

**Comment by Deathnote45** [comment]
@usha-madithati I want to work on this issue. please assign me this issue.
my profile: https://www.linkedin.com/in/shuvangi-de-369071236/

**Comment by usha-madithati** [comment]
> @usha-madithati I want to work on this issue. please assign me this issue.
> my profile: https://www.linkedin.com/in/shuvangi-de-369071236/
I have assigned the issue to you. Please do work efficiently.

**Comment by Deathnote45** [comment]
ok. Thank you so much.

**Comment by usha-madithati** [comment]
> ok. Thank you so much.

@Deathnote45 can you share your whatsapp details so that I can't contact you through that and it would be easy for our team to reach you .please do share your whatsapp details asap. 
Thank you

**Comment by Gokilp** [comment]
can also join the team  im also helping to them @Gokilp  please also asssign to me we are working together

**Comment by Deathnote45** [comment]
@usha-madithati where can I share you my details?

**Comment by usha-madithati** [comment]
> @usha-madithati where can I share you my details?

I will share your my email there you can share your whatsapp contact.
Email -id ushamadithati712@gmail.com

**Comment by Deathnote45** [comment]
@usha-madithati already sent my details to you.

**Comment by usha-madithati** [comment]
> can also join the team  im also helping to them @Gokilp  please also asssign to me we are working together @usha-madithati 
> 
> 

Can you share the details of the person you are working with@Gokilp

**Comment by usha-madithati** [comment]
> @usha-madithati already sent my details to you.

Thank you I will contact you shortly .

**Comment by Gokilp** [comment]
how can i contact

**Comment by usha-madithati** [comment]
> can also join the team im also helping to them @Gokilp please also asssign to me we are working together @usha-madithati

Heyyy!!!@gokilp can you drop your whatsap detals.
