### ISSUE TITLE
Feature Request : Improve UI for Improve your Product Inventory

### ISSUE THREAD

**Issue by KomalMaurya** [usha-madithati/esmart.github.io#433]
### Describe the feature

Improve your Product Inventory is very boring and I want to make it more interactive....!!!

Name : Komal Maurya
Role : Contributor in GSSoC'24
GitHub Profile Link : https://github.com/KomalMaurya

Please assign this issue to me!

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f56a88f4-1d5a-48d7-9e69-219bbc449d27)
![image](https://github.com/user-attachments/assets/b93328ae-b1b8-4975-bc61-8b6b9b10f574)
![image](https://github.com/user-attachments/assets/ba3d0a20-5c39-40a0-99e7-2ca9b3a09bf6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by KomalMaurya** [comment]
@usha-madithati Please assign this issue to me as I would like to make these cards very interactive....

**Comment by KomalMaurya** [comment]
@usha-madithati How about this ?

![ss1](https://github.com/user-attachments/assets/b79dcec7-24c3-4089-a085-79eab9b450f0)

**Comment by KomalMaurya** [comment]
@usha-madithati I won't change the images u see...I will just change the UI of cards as it taking lot of space....I'll align them in one frame and will also enhance their design.
![ss2](https://github.com/user-attachments/assets/a9c864f9-4805-42a4-869a-7bfe2d286efe)

**Comment by KomalMaurya** [comment]
@usha-madithati How about this ?
![ss1](https://github.com/user-attachments/assets/b4f0d0af-f8fe-4181-bff3-96e479dc9805)

**Comment by usha-madithati** [comment]
> @usha-madithati How about this ?
> ![ss1](https://github.com/user-attachments/assets/b4f0d0af-f8fe-4181-bff3-96e479dc9805)
>
If needed I will contact you 
Thank you

**Comment by KomalMaurya** [comment]
@usha-madithati So should I close this issue?

**Comment by usha-madithati** [comment]
> @usha-madithati So should I close this issue?

I will close
