### ISSUE TITLE
DOC: Improve features and elaborate the "Set Up and Installation" section in README.md

### ISSUE THREAD

**Issue by VShalini01** [usha-madithati/esmart.github.io#44]
### What's wrong with the existing documentation

The "Set Up and Installation" section can be elaborated and explained well for better understanding. Also the text of the GSSoC logo could be improved.
I am interested to make the contributions. @usha-madithati Please assign the issue to me ma'am.

### Add ScreenShots

![Screenshot 2024-05-11 145501](https://github.com/usha-madithati/esmart.github.io/assets/163420743/e170965a-837e-47c4-b719-1bdc0eb04173)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nandu-99** [comment]
please assign me this issue, i want to work on this

**Comment by shruti110503** [comment]
Please assign this to me. I want to contribute.
