### ISSUE TITLE
Improve the Navigation bar

### ISSUE THREAD

**Issue by MadhunishaBala** [usha-madithati/esmart.github.io#45]
### Describe the feature

The current navigation bar is quite pale and its not heading to the correct pages, I can improve that under GSSOC"24

### Add ScreenShots

This is what it looks like currently
![image](https://github.com/usha-madithati/esmart.github.io/assets/127708789/a991cdfa-d0df-44e3-9fcf-1ff12688d682)

I can make it look in this style

![image](https://github.com/usha-madithati/esmart.github.io/assets/127708789/7f0971f1-0d58-4719-8011-b19023f5ef6f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshitpnd12** [comment]
i want to work on this issue

**Comment by Anou25** [comment]
Hi, I want to work on this issue please assign it to me

**Comment by Paavni-Goyal** [comment]
Hey, I would like to work on the same. Can you please assign this to me under GSSoC'24.

**Comment by Shaurya0765** [comment]
I can work on this as I have done it already in my website
