### ISSUE TITLE
Feat:Sticky Nav Bar

### ISSUE THREAD

**Issue by Saipradyumnagoud** [usha-madithati/esmart.github.io#463]
### Describe the feature

Making The nav bar sticky

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saipradyumnagoud** [comment]
@usha-madithati Please assign me the issue

**Comment by usha-madithati** [comment]
I have not planned that

**Comment by Saipradyumnagoud** [comment]
@usha-madithati But when we scroll the website down we are not able to acces to the NAV bar so i fell like it is needed to the website

**Comment by usha-madithati** [comment]
We are planning to add scroll to top feature

**Comment by Saipradyumnagoud** [comment]
Can i work on it then?? @usha-madithati

**Comment by usha-madithati** [comment]
Heyyy@Saipradyumnagoud if you are interested you can work on this issue

**Comment by Saipradyumnagoud** [comment]
@usha-madithati Yes i am intrested i will work

**Comment by usha-madithati** [comment]
Ok you can start your work . I will assign. You

**Comment by Saipradyumnagoud** [comment]
> Ok you can start your work . I will assign. You

assign me i have worked on it
