### ISSUE TITLE
Feat:Back To Top Button

### ISSUE THREAD

**Issue by Saipradyumnagoud** [usha-madithati/esmart.github.io#476]
### Describe the feature

Adding Back To Top Button

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saipradyumnagoud** [comment]
@usha-madithati Can you please assign me the issue

**Comment by Saipradyumnagoud** [comment]
@usha-madithati Your website Does not have a back to top button hope this is helpful mam.

**Comment by usha-madithati** [comment]
We have a sticky nav bar now . Then why do we even need scroll to top button.
It would be unnecessary.

**Comment by Saipradyumnagoud** [comment]
@usha-madithati  but the websites have back top button mam hope this is help full mam.

**Comment by usha-madithati** [comment]
> @usha-madithati  but the websites have back top button mam hope this is help full mam.

If it's that much necessary I will contact you . Thank you .
