### ISSUE TITLE
Feat: Styling the privacy page

### ISSUE THREAD

**Issue by ayush-848** [usha-madithati/esmart.github.io#488]
### Describe the feature

I want the design the page with the website theme in mind "SMART" 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/4c41a56e-c616-4929-963e-337dd72b9b97)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
@usha-madithati can you assign this issue to me

**Comment by omrakibe** [comment]
pls assign this issue to me!!
