### ISSUE TITLE
Give an efficient responsive UI 

### ISSUE THREAD

**Issue by usha-madithati** [usha-madithati/esmart.github.io#5]

**Comment by nandu-99** [comment]
Please assign this issue to me, i have made the local setup, there are many ui breakdowns in the website, i think i can resolve this issues

**Comment by usha-madithati** [comment]
Iam happy to know that you are willing to come forward and contribute to us
. But as far as now I can't have the authority to assign any work to you .
But I can say that I would recommend you . I will once ask project manager
and I will contact you .
 Thank you

**Comment by nandu-99** [comment]
thank you

**Comment by usha-madithati** [comment]
Share Your linked in and git hub id

**Comment by nandu-99** [comment]
linkedIn: (vivekananda Pottbathini) https://www.linkedin.com/in/vivekananda-pottabathini-814200288/
Github: nandu-99 (https://github.com/nandu-99)

**Comment by anushkapal28** [comment]
Hi, I've set up the local environment. Please assign the UI breakdown issues to me. Confident I can resolve them efficiently. Thanks!

**Comment by usha-madithati** [comment]
Good to hear that I will get back to you
Thank you .

**Comment by usha-madithati** [comment]
Good evening,
As you can see that I have assigned issue to @nandu-99. I hope we can work
together and contribute more to our project. I would like to officially
invite you for our project . Welcome @nandu-99.
Share your WhatsApp details as  it would be more efficient to communicate
and connect with all other contributors too.
Thank you .

**Comment by nandu-99** [comment]
thank you so much

**Comment by usha-madithati** [comment]
Share me your contact number

**Comment by nandu-99** [comment]
Mobile number: +91 6309199666

**Comment by Gokilp** [comment]
please assign to me #gssoc24

**Comment by usha-madithati** [comment]
Are you ok to work along with other person . Because it would be difficult
for one person to design enti UI . So I thought of taking 2 mem for this
issue. If you are ok with it. Just let me know.
Thank you

**Comment by Gokilp** [comment]
Okie mam

**Comment by usha-madithati** [comment]
Ok then I will let you know

**Comment by Gokilp** [comment]
please assign to me

**Comment by iamrudhresh** [comment]
Please assign this issue to me, under the GSSOC'24

**Comment by nakshatravyas** [comment]
I am a MERN developer and i can do design as well. kindly assign me the issue
