### ISSUE TITLE
Feat: Add a feature to write a grocery item not in list.

### ISSUE THREAD

**Issue by aaryancodeshere** [usha-madithati/esmart.github.io#52]
### Describe the feature

# Adding Grocery Name

### In the add grocery section, the user must select the grocery's name from the existing list. There should be an option to add a name by typing and adding it as an option for the future.

It can be implemented using HTML, CSS and JavaScript.

### Add ScreenShots

<img width="1080" alt="Screenshot 2024-05-11 at 8 03 12 PM" src="https://github.com/usha-madithati/esmart.github.io/assets/124273822/92fe7f65-5550-4276-9885-072cb6a73d09">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aaryancodeshere** [comment]
Please assign it to me @usha-madithati

**Comment by usha-madithati** [comment]
Thank you but we are thinking of designing a qr scanner so that users need not to select any grocery items. so i dont think we really need that. 
Thank you
