### ISSUE TITLE
Create a service Page

### ISSUE THREAD

**Issue by 07Shivam08** [usha-madithati/esmart.github.io#58]
I would like to create service page as it is missing and make it more informative for the users. I am a GSSOC'24 Contributor kindly assign this issue to me.
 Thanks -:)

**Comment by deepakmaur** [comment]
Kindly Assign this Issue to Me Under GGSOC'24

**Comment by its-kritika** [comment]
Hey @usha-madithati i can design the service page. I have experience in front end development and i can make it responsive as well.

**Comment by Aleena-Memon** [comment]
Please assign it to me so that i can work under GSSOC'24.
