### ISSUE TITLE
Feat: Create about page

### ISSUE THREAD

**Issue by Ridhima10** [usha-madithati/esmart.github.io#60]
### Describe the feature

I would like to create the about page of the website so that it will be easy for users to know the details / information of the website

### Add ScreenShots

![Screenshot 2024-05-11 235828](https://github.com/usha-madithati/esmart.github.io/assets/85826117/ac0291e9-710f-4cc4-a016-a373ccba6452)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kumud14** [comment]
I would like to solve this issue please assign this to me

**Comment by Ayushvishwakarma04** [comment]
Hello! 😊 I'd appreciate being assigned this task for GSSoC 24.

**Comment by drashtigit** [comment]
@usha-madithat .Can you please assign me this issue under GSSOC'24

**Comment by meghana9044** [comment]
@usha-madithati I'm interested in contributing to Smart Saver under GSSOC'24. Please assign this issue to me.

Welcome to SuperSaver, your ultimate destination for incredible savings on a wide range of products! Our journey began with a simple idea: to make shopping more affordable and enjoyable for everyone.
Join the millions of savvy shoppers who have already discovered the joys of shopping smart with SuperSaver. Start saving today!

This would be the description with a eye-catchy background.
