### ISSUE TITLE
Responsive Navbar With Animation

### ISSUE THREAD

**Issue by gupta-ritik** [usha-madithati/esmart.github.io#62]
### Describe the feature

i want to change the navbar design with some animation included and also I want to add footer in this website to made attractive towards User of the Website 
please assign this work to me

### Add ScreenShots

![nav](https://github.com/usha-madithati/esmart.github.io/assets/127002992/6e5194fc-dd3c-4796-800c-bd81d98c1365)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GauriGA** [comment]
@usha-madithati Could you please assign this issue to me under the GSSOC'24 label?
