### ISSUE TITLE
Addition FAQs section 

### ISSUE THREAD

**Issue by gupta-ritik** [usha-madithati/esmart.github.io#63]
### Describe the feature

I want to add an FAQs section to this website.

**Importance of FAQs section**
A FAQ section on a website is vital for user experience, reducing support queries, and building trust. It offers quick answers to common questions, streamlining navigation and saving time for users. By addressing concerns upfront, it reduces the need for contacting customer support, optimizing resources. The section's clarity and organization enhance user satisfaction and credibility, showcasing transparency and care for customer needs. Additionally, FAQs contribute to SEO by incorporating relevant keywords. They serve as educational tools, empowering users with valuable insights into products, services, or industries. Ultimately, a well-structured FAQ section is essential for a user-friendly, trustworthy, and informative website.

### Add ScreenShots

![faq](https://github.com/usha-madithati/esmart.github.io/assets/127002992/764505fa-4e28-4865-aca2-63161d8859e9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by savyaaa** [comment]
Hi! I'd like to work on this issue under GSSOC '24. Please assign it to me.
