### ISSUE TITLE
Feat: Add a slider featuring images in home page

### ISSUE THREAD

**Issue by its-kritika** [usha-madithati/esmart.github.io#64]
### Describe the feature

I can add an image slider which will interact with the user as they land on the home page

An image slider looks attractive and makes the web page visually engaging and user friendly. We can toggle among multiple images that can display different purposes of the website, call-to-action buttons. Image sliders can be used to tell a visual story and take visitors on a journey. It will overall improve aesthetics, usability, and effectiveness of the website. 
I have shared SS of image slider, I have implemented in my project.

### Add ScreenShots

![Screenshot (373)](https://github.com/usha-madithati/esmart.github.io/assets/144522556/f69e0801-a370-47ea-aac0-d2c4cdba4731)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aleena-Memon** [comment]
Please assign it to me so that i can work under GSSOC'24.
