### ISSUE TITLE
Feat : adding the meta tag to improve the seo 

### ISSUE THREAD

**Issue by 0xabdul** [usha-madithati/esmart.github.io#65]
### Describe the feature

The html page contains meta tag to improve the seo for ex : adding the meta elements like meta description, meta keywords, then meta author to improve the seo problem✨

### Add ScreenShots

![IMG_20240512_014640](https://github.com/usha-madithati/esmart.github.io/assets/119418867/37cb72de-06e9-480f-8a2d-50c301015942)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Rit2402** [comment]
hey mam i want to work on this project please assign to me

**Comment by 0xabdul** [comment]
I work on this issue please assign to me
