### ISSUE TITLE
BUG: Grammatical error in CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by samarpitadas** [usha-madithati/esmart.github.io#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the **"Enforcement Guidelines"** section, there is a grammatical error. 

"Consequence: A warning with **consequences** for continued behavior." Here, the word "consequences" should be singular, as it is referring to the consequences of the warning.  

The correct sentence must be "Consequence: A warning with **consequence** for continued behavior." I will make the necessary changes if the issue is assigned to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by samarpitadas** [comment]
@usha-madithati Please assign this issue to me under GSSOC'24. I will also improve the documentation

**Comment by kip-07** [comment]
Subject: Task Assignment Request for GSSOC 24: Readme File Grammar Corrections and Documentation Enhancement

Dear @usha-madithati 

I hope this message finds you well. I am reaching out to express my interest in taking on a task for GSSOC 24. After reviewing our project's documentation, I've noticed several grammatical errors in the readme file that I believe need correction. Additionally, I would like to enhance the overall documentation with my exceptional English skills to make it more engaging and easy to read.

I kindly request that you assign me this task so I can contribute to improving the quality of our project's documentation. Furthermore, I would appreciate it if you could label this issue appropriately for tracking purposes.

Warm regards,
Khushi

**Comment by n14rishitha** [comment]
Hi @usha-madithati 
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3
