### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [usha-madithati/esmart.github.io#71]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by Anumallasarayu123** [comment]
Contributing.md file is very important .This file makes the Contributor to work on the project without any problem.
Can u please assign me the issue under GSSOC 24
I have very clear idea about working on the repositories .I think I will create a good contribution file.

**Comment by n14rishitha** [comment]
hi @usha-madithati 
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3
