### ISSUE TITLE
DOC: Update README for Improved Documentation

### ISSUE THREAD

**Issue by jinx-vi-0** [usha-madithati/esmart.github.io#73]
### What's wrong with the existing documentation

The current README is not visually appealing and also lacks some key details like
- how to run project locally
- contribution details

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/120160355/28330540-b7b6-492b-b9c6-56004a7afc15)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Riyasharma28** [comment]
Please assign this issue to me (Riyasharma28) under GSSoC'24.

**Comment by jinx-vi-0** [comment]
hey @usha-madithati , I have open this issue so please assign this issue to me so I can start working on it.
