### ISSUE TITLE
ADDING DARK THEME

### ISSUE THREAD

**Issue by AtharvaShinde253** [usha-madithati/esmart.github.io#74]
Can add a dark theme button to add a more lively experience to users.
please assign me with this issue.

**Comment by savyaaa** [comment]
Hi! I think adding a theme button will enhance the user experience. And I wanna work on it under GSSOC '24. Please assign me this issue.

**Comment by shruti110503** [comment]
hi! I want to work on adding a dark theme button for better user experience under GSSOC'24. Please assign this issue to me.

**Comment by SkandSingh** [comment]
Hii, can you please assign this task to me under GSSoc'23. I have also done this thing in many of my projects!!

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!

**Comment by student-dv** [comment]
I would like to work on this issue, can you please assign this to me.

**Comment by PadmalathaKasireddy** [comment]
I would love to contribute for this issue of adding Dark Theme , I'm keen to help enhance the website features and user experience. Looking forward to the opportunity to discuss further.

Best regards,

**Comment by Akansha1409** [comment]
Hey, there! , i think it is a great project 
I want  to make it more attractive by adding dark theme
kindly assign me this issue.
