### ISSUE TITLE
DOC: Spell Check

### ISSUE THREAD

**Issue by shruti110503** [usha-madithati/esmart.github.io#78]
### What's wrong with the existing documentation

The spelling of alarm and daily are wrong in the about page. Please assign this issue to me. I will also work on enhancing the whole about documentation.

### Add ScreenShots

![Screenshot 2024-05-12 183909](https://github.com/usha-madithati/esmart.github.io/assets/118251562/4621d43c-8604-4fff-bef6-5de253d6324e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meghana9044** [comment]
@usha-madithati Please assign this issue to me under GSSOC'24, i will enhance the documentation text.

**Comment by khushi497** [comment]
Can you please assign me the issue?

**Comment by Maheshwari-Love** [comment]
can you please assign this tast to me I am already working on this repo

**Comment by shiuli-19** [comment]
Can you please assign this task to me.
