### ISSUE TITLE
Feat: Web App Deployment

### ISSUE THREAD

**Issue by Manishak798** [usha-madithati/esmart.github.io#79]
### Describe the feature

As there is no link provided for the user to visit the main web app. I suggest to deploy it somewhere to engage contribution and user trafic. I am a **MENTOR** in **GSSOC'24** raising this feature for contributors to kickstart there contribution journey.

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/90680330/440657c5-8d97-458c-a10f-41abe94cbbee)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Riyasharma28** [comment]
Please assign this issue to me (Riyasharma28) under GSSoC'24.
