### ISSUE TITLE
Create Services page, with heavy use of CSS #GSSoC 24

### ISSUE THREAD

**Issue by SamarupBhattacharya** [usha-madithati/esmart.github.io#83]
### Describe the feature

I would like to add a Services Page to your website, that will be heavily adourned with CSS features. I would like a lot if add the labels of **GSSoC 24** and **level 2** to this issue. Also, please assign this issue to me and I will get to it right away.

### Add ScreenShots

I like designing websites using CSS. For reference, I am attaching a screenshot of the webpage that I created in my previous contribution.
![SS](https://github.com/usha-madithati/esmart.github.io/assets/138982308/8d96d312-5591-43a9-bfe3-08e078aefece)
I have used CSS features such as flex-box and pseudo-elements and classes like after and hover 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by devanshaggarwal03** [comment]
Please assign me this issue under GSSoC'24
