### ISSUE TITLE
BUG: not responsive

### ISSUE THREAD

**Issue by AkshatJangid787** [usha-madithati/esmart.github.io#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

make it responsive and attractive

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aryakhot** [comment]
hello @usha-madithati, id like to work on this issue. could you please assign this issue to me?
