### ISSUE TITLE
Enhancement: Add a fav icon

### ISSUE THREAD

**Issue by MrPC7** [usha-madithati/esmart.github.io#87]
### Describe the feature

I will add fav icon to this website for all the devices.
Please allow me to work on this enhancement.

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/91939963/0ba53f0f-0802-46f8-9ac1-4c9da81f9fc2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Riyasharma28** [comment]
Please assign this issue to me (Riyasharma28) under GSSoC'24.

**Comment by Divyaraj33** [comment]
I would like to work on this project. Please assign it to me.

**Comment by CHITRA2445** [comment]
hi @usha-madithati . i am interested in working with the issue. please assign it to me

**Comment by Tanu2205** [comment]
Can you please assign me this issue?

**Comment by Ved8290** [comment]
I want to work on this issue
