### ISSUE TITLE
DOC: Spelling mistakes in README.md file

### ISSUE THREAD

**Issue by Maheshwari-Love** [usha-madithati/esmart.github.io#90]
### What's wrong with the existing documentation

There are 2-3 spelling mistake in ReadMe.md file
In  Key features the spelling of:
1) Management
In About sections
2)Daily
3)Alarm 

### Add ScreenShots

![Screenshot 2024-05-13 092825](https://github.com/usha-madithati/esmart.github.io/assets/142833275/e0ed7d25-920a-4b2c-ab18-1cfe861a9021)
![Screenshot 2024-05-13 092802](https://github.com/usha-madithati/esmart.github.io/assets/142833275/8cbf9b1f-2766-4d6d-bd9d-f8b7d1880ef0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@usha-madithati I want to solve this issue ,can you please assign this task to me, I have gone through documentation properly and found these small mistakes

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!

**Comment by ashish027120** [comment]
@usha-madithati Can You Please Assign Me This Issue Please , I Would Like To Work On This .
