### ISSUE TITLE
Design Refinement

### ISSUE THREAD

**Issue by student-dv** [usha-madithati/esmart.github.io#91]
### What's wrong with the existing documentation

The website lacks visual polish and refinement. Key elements such as layout, typography, and color scheme seem underdeveloped. Navigation and user experience are likely to be challenging due to limited structure and organization.

1. Implement a visually appealing layout with clear hierarchy and spacing.

2. Choose appropriate typography and color palette to enhance readability and brand identity.

3.Ensure consistency across the website in font sizes, styles, and color usage.

I would like to work on these issues. Please assign it to me.

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
