### ISSUE TITLE
Font improvement can be done.Feat:

### ISSUE THREAD

**Issue by navnit0706** [usha-madithati/esmart.github.io#93]
### Describe the feature

Fonts play an important role in a website's design and user experience. Fonts impact the overall user experience of a website. A well-chosen font improves user satisfaction by making the content more accessible and enjoyable to read. On the other hand, poorly selected fonts can frustrate users and drive them away from the site.
Describe the solution you'd like
Choose Appropriate Fonts:
Select fonts that align audience preferences, and content tone. Consider factors like readability and emotional impact. Choose fonts that support a wide range of languages and character sets.
Optimize Font Size and Spacing:
Ensure that text is adequately sized for comfortable reading on various screen sizes. Adjust line spacing (line height) to improve readability and prevent text from appearing cramped or crowded. Increase the font size and adjust the contrast ratio to improve readability.

### Add ScreenShots

![ae8ac432-04c4-4d00-8dda-476238eb48fa](https://github.com/usha-madithati/esmart.github.io/assets/162101737/8f7b4724-4f31-44e3-ba99-d174c73f19fc)
We Can use these fonts for better website design and better user experience.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by navnit0706** [comment]
I'm a GSSOC 24 Contributor , pls assign me this issue.

**Comment by Aryakhot** [comment]
hello @usha-madithati, id like to work on this issue. could you please assign this issue to me?
