### ISSUE TITLE
BUG: Image not available

### ISSUE THREAD

**Issue by tanu-agarwal0101** [usha-madithati/esmart.github.io#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Image not visible ( no alt either)
![image](https://github.com/usha-madithati/esmart.github.io/assets/162132053/1ecf875c-fac0-4ad7-9d2b-bcc30b7d2d25)

There is no padding at the sides either.
![image](https://github.com/usha-madithati/esmart.github.io/assets/162132053/18c88e92-7b52-46dd-9040-e141e994bab7)

The hovering effect does not really matches with the theme of the website. I would like to play with it a bit
![image](https://github.com/usha-madithati/esmart.github.io/assets/162132053/4665c5f3-8461-4d13-911c-16d48149a735)

Please assign me to work on these under GSSOC'24
Please let me know if I can help with anything.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Divi-1026** [comment]
Hey !! Can you plzz assign this issue to me . I am eagerly waiting to solve this issue
