### ISSUE TITLE
Feat: No about us , contact us feature pages are there, also absence of header and footer sections 

### ISSUE THREAD

**Issue by curecode11** [usha-madithati/esmart.github.io#95]
### Describe the feature

Can make the about us , contact us page so that customer can know well about us what we do and how we do.
Also add header and footer sections with hyperlinks for fast going around the site.

### Add ScreenShots

![image](https://github.com/usha-madithati/esmart.github.io/assets/118065498/110185a1-dc71-4051-80d6-1fe48b6404f4)
![image](https://github.com/usha-madithati/esmart.github.io/assets/118065498/00423c99-17f9-4a40-852d-1dd0cc09906e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
