### ISSUE TITLE
Feat: Redesigning of the whole UI of the website

### ISSUE THREAD

**Issue by nakshatravyas** [usha-madithati/esmart.github.io#99]
### Describe the feature

I am pleased to present a proposal for a comprehensive redesign of our website's user interface. This means we're making big improvements to everything, from the home page to log in and sign up page. Plus, I've made sure to redesign important pages like the notification settings and QR code scan page and make sure that they are easier to use.

We're not just making things look better, we're making sure our website is easy for everyone to use and enjoy. By updating how it looks and works, we're making sure people have a great time when they visit us online.

### Add ScreenShots

This is new the design: [https://www.figma.com/design/naU9W2cQQa04wB6WsEjkr2/Untitled?node-id=0%3A1&t=DazRyOMA1k4rRDTr-1](url)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by usha-madithati** [comment]
Thank You @nakshatravyas for your work . We are pleased to have you in the team.

**Comment by simi-9112** [comment]
Hello @usha-madithati I would also like to contribute to ui designing of your project
You can checkout my previous designs here
https://drive.google.com/drive/folders/1_96R2o7S2-EZ0r8vpwI7ChpJypkHxzz5
hope u provide me with an opportunity to work on the issue as wll

**Comment by Nikhilkumar111** [comment]
Hello @usha-madithati I would also like to contribute to ui designing of your project
hope u provide me with an opportunity to work on the issue as well.
